version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: bookitory-mysql
    restart: unless-stopped
    ports:
      - "13306:3306"
    env_file:
      - .env
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /tmp/mount/mysql:/var/lib/mysql
      - ./src/database/:/docker-entrypoint-initdb.d/